Check API level for get instructions in constant canonicalizer
Avoid moving get instructions in the constant canonicalizer if the
field type is not safe to reference on all supported API levels.
The get will most likely be guarded by an API level check and
moving it can then cause java.lang.NoClassDefFoundError.

Fixes: b/331556916
Change-Id: I5e6e736492af9249971ef594e07fdc3fb3280e6c